DATA:
    data_name: ogbn-arxiv
    deg4feat: True

DATALOADER:
    NUM_WORKERS: 0

MODEL: 
    num_hidden: 512
    num_layers: 2
    nhead: 2
    activation: prelu
    attn_drop: 0.1
    feat_drop: 0.2
    norm: layernorm
    pooler: mean
    beta_schedule: sigmoid
    beta_1: 0.0001
    beta_T: 0.02
    T: 1000

SOLVER:
    optim_type: adam
    optim_type_f: adamw
    alpha: 0.8
    decay: 35
    LR: 0.0002
    LR_f: 0.01
    weight_decay: 0
    weight_decay_f: 5e-4
    MAX_EPOCH: 100
    max_epoch_f: 500

DEVICE: cuda
seeds:
    - 11
eval_T:
    - 50
    - 100
    - 200

